---
- name: "Install packages"
  retries: 3
  delay: 10
  until: output is success
  register: output
  ansible.builtin.package:
    update_cache: true
    name:
      - "rkhunter"

- name: "Import Rkhunter configuration"
  ansible.builtin.template:
    src: "templates/rkhunter.conf.j2"
    dest: "/etc/rkhunter.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: "Install others packages"
  when: install_rkhunter__create_cron_job
  retries: 3
  delay: 10
  until: output is success
  register: output
  ansible.builtin.package:
    update_cache: true
    name:
      - "cron"
      - "mailutils"
      - "colorized-logs"
      - "kbtin"

- name: "Send automatics report with cron"
  when: install_rkhunter__create_cron_job | default(false)
  block:
    - name: "Check if a cron file exist"
      register: cron_file
      ansible.builtin.stat:
        path: "/etc/cron.d/ansible_install_rkhunter__and_send_report"

    - name: "Configure automatic reports with cron"
      when: not cron_file.stat.exists
      ansible.builtin.cron:
        name: "ansible - send rkhunter email reports"
        weekday: "{{ install_rkhunter__cron_job_weekday }}"
        minute: "{{ install_rkhunter__cron_job_minute }}"
        hour: "{{ install_rkhunter__cron_job_hour }}"
        user: "root"
        job: "rkhunter --update && rkhunter --propupd 2>&1 && sudo rkhunter --checkall --skip-keypress 2>&1 | ansi2html | mail -a 'MIME-Version: 1.0' -a 'Content-Type: text/html; charset=iso-8859-1' -s \"Rkhunter reports of $(hostname -f)\" {{ install_rkhunter__report_email_address }}"
        cron_file: "ansible_install_rkhunter__send_reports"
