---
- name: "Converge"
  hosts: "cicd-debian-11"
  tasks:

    - name: "Include labocbz.install_rkhunter"
      tags:
        - "labocbz.install_rkhunter"
      vars:
        install_rkhunter__create_cron_job: "{{ inv_install_rkhunter__create_cron_job }}"
        install_rkhunter__cron_job_weekday: "{{ inv_install_rkhunter__create_cron_job }}"
        install_rkhunter__cron_job_minute: "{{ inv_install_rkhunter__cron_job_minute }}"
        install_rkhunter__cron_job_hour: "{{ inv_install_rkhunter__cron_job_hour }}"
        install_rkhunter__report_email_address: "{{ inv_install_rkhunter__create_cron_job }}"
      ansible.builtin.include_role:
        name: "labocbz.install_rkhunter"
